# Generated by Django 4.2.3 on 2023-07-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubemodel',
            old_name='transcript',
            new_name='summary',
        ),
    ]
