# Generated by Django 4.2.3 on 2023-07-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_transcript_youtubemodel_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubemodel',
            name='lang',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubemodel',
            name='transcripts',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
